language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
env:
- ENV_NAME=$(./.travis/get_branch_env_name.sh)
before_script:
- wget "https://www.uncleclapton.me/static/dwb/app.${ENV_NAME}.config.js"
- npm install -g gulp-cli
script:
- gulp --env ${ENV_NAME} --buildid ${TRAVIS_COMMIT}
addons:
  ssh_known_hosts: cheddar.fuelrats.com
notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
    - irc.us.fuelrats.com#rattech
    nick: TravisCI
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{result}"
    - 'Change view : %{compare_url}  Build details : %{build_url}'
before_deploy:
- openssl aes-256-cbc -K $encrypted_0b2fcf215327_key -iv $encrypted_0b2fcf215327_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete --delete-after --quiet $TRAVIS_BUILD_DIR/deploy/ fuelrats@cheddar.fuelrats.com:/var/www/dispatch.fuelrats.com/prod
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: rsync -r --delete --delete-after --quiet $TRAVIS_BUILD_DIR/deploy/ fuelrats@cheddar.fuelrats.com:/var/www/dispatch.fuelrats.com/beta
  on:
    branch: beta
